const compassAuthors=window.COMPASS_AUTHORS||[];
const compassQuestions=window.COMPASS_QUESTIONS||[];
let compassMode='map',compassSelected=null,compassCompareA='Friedrich Nietzsche',compassCompareB='William Blake',compassQuestion=0,compassAnswers=Array(compassQuestions.length).fill(null),compassResult=null,compassSearch='',compassTestStarted=false;
const compassText=(es,en)=>lang==='es'?es:en;
const compassAvailable=()=>{const names=new Set(works.map(w=>w.author));return compassAuthors.filter(a=>names.has(a.a));};
function compassCoordLabel(axis,value){if(axis==='x')return value<-35?compassText('Sombrío','Shadowed'):value>35?compassText('Luminoso','Luminous'):compassText('Ambivalente','Ambivalent');return value>35?compassText('Formal / estético','Formal / aesthetic'):value<-35?compassText('Directo / narrativo','Direct / narrative'):compassText('Híbrido','Hybrid')}
function compassDistance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function compassNearest(point,n=5,exclude=''){return compassAvailable().filter(a=>a.a!==exclude).map(a=>({...a,d:compassDistance(a,point)})).sort((a,b)=>a.d-b.d).slice(0,n)}
function compassAuthor(name){return compassAvailable().find(a=>a.a===name)||compassAvailable()[0]}
function compassFirstReading(name){const list=works.filter(w=>w.author===name);return list.find(isEnabled)||list[0]||null}
function compassOpenAuthor(name){const w=compassFirstReading(name);if(!w)return;if(!isEnabled(w)&&w.package_id!=='mvp')setPackageEnabled(w.package_id,true);setTimeout(()=>openBook(w.id),0)}
function compassDotStyle(a){return `left:${50+a.x*.44}%;top:${50-a.y*.44}%`}
function compassMap(labels=true){
 const list=compassAvailable().filter(a=>!compassSearch||a.a.toLowerCase().includes(compassSearch.toLowerCase()));
 const resultDot=compassResult?`<span class="compass-user-dot" style="left:${50+compassResult.x*.44}%;top:${50-compassResult.y*.44}%" title="${compassText('Tu posición','Your position')}"></span>`:'';
 return `<div class="compass-plot-wrap" id="compass-plot"><span class="compass-quadrant compass-q1">${compassText('La grieta','The fracture')}</span><span class="compass-quadrant compass-q2">${compassText('La visión','The vision')}</span><span class="compass-quadrant compass-q3">${compassText('La intemperie','The open')}</span><span class="compass-quadrant compass-q4">${compassText('El relato','The tale')}</span><span class="compass-axis compass-axis-top">${compassText('FORMA · ESTETICISMO','FORM · AESTHETICISM')}</span><span class="compass-axis compass-axis-bottom">${compassText('NARRACIÓN · TRANSPARENCIA','NARRATIVE · TRANSPARENCY')}</span><span class="compass-axis compass-axis-left">${compassText('DESENCANTO','DISENCHANTMENT')}</span><span class="compass-axis compass-axis-right">${compassText('TRASCENDENCIA','TRANSCENDENCE')}</span>${list.map(a=>`<button class="compass-dot${compassSelected===a.a?' selected':''}${compassMode==='compare'&&compassCompareA===a.a?' compare-a':''}${compassMode==='compare'&&compassCompareB===a.a?' compare-b':''}" data-compass-author="${esc(a.a)}" style="${compassDotStyle(a)}" aria-label="${esc(a.a)}"></button>${labels&&(compassSelected===a.a||compassSearch)?`<span class="compass-label" style="${compassDotStyle(a)}">${esc(a.a)}</span>`:''}`).join('')}${resultDot}</div>`;
}
function compassSide(name){
 const a=compassAuthor(name);if(!a)return `<div class="compass-side"><p class="compass-empty">${compassText('Selecciona un autor en el mapa.','Select an author on the map.')}</p></div>`;
 const nearby=compassNearest(a,4,a.a),reading=compassFirstReading(a.a);
 return `<aside class="compass-side"><p class="tiny-title">${compassText('Perfil editorial','Editorial profile')}</p><h3>${esc(a.a)}</h3><p class="meta">${compassCoordLabel('x',a.x)} · ${compassCoordLabel('y',a.y)}</p><div class="compass-coords"><div class="compass-coord"><strong>${a.x>0?'+':''}${a.x}</strong><span>${compassText('desencanto ↔ trascendencia','disenchantment ↔ transcendence')}</span></div><div class="compass-coord"><strong>${a.y>0?'+':''}${a.y}</strong><span>${compassText('narración ↔ forma','narrative ↔ form')}</span></div></div><div class="compass-tags">${a.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="compass-nearby"><h4>${compassText('Vecinos en la brújula','Nearby on the compass')}</h4>${nearby.map(n=>`<button data-compass-author="${esc(n.a)}">${esc(n.a)}</button>`).join('')}</div>${reading?`<button class="book-btn compass-read" data-compass-read="${esc(a.a)}">${isEnabled(reading)?compassText('Leer una pieza →','Read a piece →'):compassText('Activar su paquete y leer →','Enable package and read →')}</button>`:''}<p class="compass-method">${compassText('Las coordenadas son una clasificación editorial de Katabasis: una herramienta para descubrir relaciones, no una propiedad objetiva del autor.','Coordinates are a Katabasis editorial classification: a discovery tool, not an objective property of the author.')}</p></aside>`;
}
function renderCompassMap(){
 const el=$('#compass-content');if(!el)return;const selected=compassSelected||'Friedrich Nietzsche';compassSelected=selected;
 el.innerHTML=`<div class="compass-layout"><section class="compass-map-card"><div class="compass-map-head"><p>${compassAvailable().length} ${compassText('autores con clasificación editorial inicial','authors with an initial editorial classification')}</p><input id="compass-search" class="compass-search" value="${esc(compassSearch)}" placeholder="${compassText('Buscar autor…','Search author…')}"></div>${compassMap(true)}</section>${compassSide(selected)}</div>`;
}
function compassScore(){let sx=0,nx=0,sy=0,ny=0;compassQuestions.forEach((q,i)=>{const v=compassAnswers[i];if(v===null)return;if(q.axis==='x'){sx+=v;nx+=2}else{sy+=v;ny+=2}});return{x:nx?Math.round(sx/nx*100):0,y:ny?Math.round(sy/ny*100):0}}
function renderCompassTest(){
 const el=$('#compass-content');if(!el)return;if(compassResult){renderCompassResult();return}
 if(!compassTestStarted){el.innerHTML=`<div class="compass-test"><div class="compass-test-intro"><p class="tiny-title">${compassText('15 preguntas · 3–4 minutos','15 questions · 3–4 minutes')}</p><h3>${compassText('Encuentra tu lugar','Find your place')}</h3><p>${compassText('No te preguntaremos qué autores te gustan. Las preguntas son sobre cómo quieres que funcione una obra: cuánto debe pesar la forma, cuánto la historia y qué relación buscas entre desencanto y trascendencia. Puedes responder en cinco grados; el centro siempre significa «depende».','We will not ask which authors you like. The questions are about how you want a work to function: how much form should matter, how much story should matter, and what relationship you seek between disenchantment and transcendence. You can answer on five levels; the center always means “it depends.”')}</p><button class="book-btn compass-start" data-compass-start>${compassText('Comenzar las 15 preguntas →','Start the 15 questions →')}</button></div></div>`;return}
 const q=compassQuestions[compassQuestion],chosen=compassAnswers[compassQuestion];
 el.innerHTML=`<div class="compass-test"><div class="compass-progress"><span style="width:${((compassQuestion+1)/compassQuestions.length)*100}%"></span></div><div class="compass-test-card compass-question"><span class="compass-question-number">${compassText('Pregunta','Question')} ${compassQuestion+1} / ${compassQuestions.length}</span><h3>${esc(lang==='es'?q.q_es:q.q_en)}</h3><div class="compass-scale-poles"><span>${esc(lang==='es'?q.l_es:q.l_en)}</span><span>${esc(lang==='es'?q.r_es:q.r_en)}</span></div><div class="compass-scale">${[-2,-1,0,1,2].map((v,i)=>`<button data-compass-answer="${v}" class="${chosen===v?'chosen':''}">${[compassText('Mucho más','Much more'),compassText('Algo más','Somewhat'),compassText('Depende','Depends'),compassText('Algo más','Somewhat'),compassText('Mucho más','Much more')][i]}</button>`).join('')}</div><div class="compass-test-nav"><button class="secondary" data-compass-prev ${compassQuestion===0?'disabled':''}>← ${compassText('Anterior','Previous')}</button><span>${compassText('No hay respuestas correctas.','There are no correct answers.')}</span><button class="secondary" data-compass-next ${chosen===null?'disabled':''}>${compassQuestion===compassQuestions.length-1?compassText('Ver resultado','See result'):compassText('Siguiente','Next')} →</button></div></div></div>`;
}
function renderCompassResult(){
 const el=$('#compass-content'),p=compassResult,matches=compassNearest(p,6);
 el.innerHTML=`<div class="compass-result"><p class="tiny-title">${compassText('Tu posición editorial','Your editorial position')}</p><h3>${compassCoordLabel('x',p.x)} · ${compassCoordLabel('y',p.y)}</h3><p>${compassText('No es una etiqueta de personalidad. Es una estimación de qué zona del mapa literario coincide mejor con las preferencias que acabas de expresar.','This is not a personality label. It estimates which part of the literary map best matches the preferences you just expressed.')}</p><div class="compass-result-position"><div><strong>${p.x>0?'+':''}${p.x}</strong><span>${compassText('Desencanto ↔ Trascendencia','Disenchantment ↔ Transcendence')}</span></div><div><strong>${p.y>0?'+':''}${p.y}</strong><span>${compassText('Narración ↔ Forma','Narrative ↔ Form')}</span></div></div><section class="compass-map-card">${compassMap(false)}</section><h4>${compassText('Tus vecinos más cercanos','Your nearest neighbors')}</h4><div class="compass-matches">${matches.map((m,i)=>`<button class="compass-match" data-compass-author="${esc(m.a)}"><span>#${i+1}</span><strong>${esc(m.a)}</strong><span>${esc(m.tags.slice(0,2).join(' · '))}</span></button>`).join('')}</div><div class="compass-test-nav"><button class="secondary" data-compass-reset>${compassText('Repetir test','Retake test')}</button><button class="book-btn" data-compass-mode="map">${compassText('Explorar el mapa →','Explore the map →')}</button></div></div>`;
}
function renderCompassCompare(){
 const el=$('#compass-content'),list=compassAvailable(),a=compassAuthor(compassCompareA),b=compassAuthor(compassCompareB),opts=sel=>list.map(x=>`<option value="${esc(x.a)}" ${x.a===sel?'selected':''}>${esc(x.a)}</option>`).join('');
 el.innerHTML=`<div class="compass-compare"><div class="compass-compare-card"><p class="tiny-title">${compassText('Dos sensibilidades','Two sensibilities')}</p><h3>${compassText('Comparar autores','Compare authors')}</h3><div class="compass-compare-selects"><label>${compassText('Autor A','Author A')}<select id="compass-a">${opts(a.a)}</select></label><span class="compass-vs">↔</span><label>${compassText('Autor B','Author B')}<select id="compass-b">${opts(b.a)}</select></label></div><div class="compass-compare-summary"><div class="compass-author-box"><h4>${esc(a.a)}</h4><p>${compassCoordLabel('x',a.x)} · ${compassCoordLabel('y',a.y)}</p><div class="compass-tags">${a.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><div class="compass-author-box"><h4>${esc(b.a)}</h4><p>${compassCoordLabel('x',b.x)} · ${compassCoordLabel('y',b.y)}</p><div class="compass-tags">${b.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div></div><div class="compass-map-card" style="margin-top:15px">${compassMap(false)}</div><p class="compass-method">${compassText(`Distancia editorial aproximada: ${Math.round(compassDistance(a,b))} puntos. Una distancia alta no significa oposición de calidad: solo que Katabasis los sitúa lejos en estos dos ejes.`,`Approximate editorial distance: ${Math.round(compassDistance(a,b))} points. A large distance does not mean an opposition in quality: only that Katabasis places them far apart on these two axes.`)}</p></div></div>`;
}
function renderCompass(){
 const root=$('#compass-view');if(!root)return;
 root.innerHTML=`<div class="compass-inner"><div class="compass-hero"><div><p class="tiny-title">${compassText('Proyecto C · borrador funcional','Project C · functional draft')}</p><h2 id="compass-title" tabindex="-1">${compassText('Brújula','Compass')}</h2><p>${compassText('Un mapa para descubrir autores por sensibilidad literaria. El eje vertical va de narración transparente a formalismo y esteticismo; el horizontal, de desencanto a trascendencia.','A map for discovering authors by literary sensibility. The vertical axis runs from transparent narrative to formalism and aestheticism; the horizontal from disenchantment to transcendence.')}</p></div><p class="compass-editorial">${compassText('Importante: estas posiciones son decisiones curatoriales de Katabasis, discutibles y revisables. Sirven para navegar; no pretenden reducir un autor a dos números.','Important: these positions are Katabasis curatorial judgments, debatable and revisable. They are for navigation; they do not claim to reduce an author to two numbers.')}</p></div><nav class="compass-tabs"><button data-compass-mode="map" aria-pressed="${compassMode==='map'}">${compassText('Explorar mapa','Explore map')}</button><button data-compass-mode="test" aria-pressed="${compassMode==='test'}">${compassText('Haz match conmigo','Match me')}</button><button data-compass-mode="compare" aria-pressed="${compassMode==='compare'}">${compassText('Comparar autores','Compare authors')}</button></nav><div id="compass-content"></div></div>`;
 if(compassMode==='test')renderCompassTest();else if(compassMode==='compare')renderCompassCompare();else renderCompassMap();
}
const compassBaseSwitch=switchPage;
switchPage=function(nextPage){
 const cv=$('#compass-view'),cb=$('#compass-open');
 if(nextPage!=='compass'){if(cv)cv.hidden=true;if(cb){cb.classList.remove('active');cb.setAttribute('aria-current','false')}return compassBaseSwitch(nextPage)}
 page='compass';$('.feed-wrap').hidden=true;$('#catalog-view').hidden=true;$('#packages-view').hidden=true;$('#favorites-view').hidden=true;$('#workshop-view').hidden=true;if(cv)cv.hidden=false;
 for(const id of ['home','catalog-open','packages-open','favorites-open','workshop-open']){$('#'+id)?.classList.remove('active');$('#'+id)?.setAttribute('aria-current','false')}
 cb?.classList.add('active');cb?.setAttribute('aria-current','page');wheelTotal=0;wheelUsed=false;touchStart=null;translateUI();renderCompass();$('#compass-title')?.focus();
};
const compassBaseTranslate=translateUI;
translateUI=function(){compassBaseTranslate();const b=$('#compass-open');if(b){b.querySelector('span').textContent=compassText('Brújula','Compass');b.setAttribute('aria-label',compassText('Brújula literaria','Literary compass'))}if(page==='compass'){$('#room-title').textContent=compassText('Brújula','Compass');$('#top-count').textContent=compassText('Mapa de sensibilidades literarias','Map of literary sensibilities')}};
const compassBaseSetLanguage=setLanguage;
setLanguage=function(l){compassBaseSetLanguage(l);if(page==='compass')renderCompass()};
$('#compass-open').onclick=()=>switchPage('compass');
document.addEventListener('click',e=>{
 const mode=e.target.closest('[data-compass-mode]');if(mode){compassMode=mode.dataset.compassMode;renderCompass();return}
 const author=e.target.closest('[data-compass-author]');if(author){compassSelected=author.dataset.compassAuthor;compassMode='map';renderCompass();return}
 const read=e.target.closest('[data-compass-read]');if(read){compassOpenAuthor(read.dataset.compassRead);return}
 if(e.target.closest('[data-compass-start]')){compassTestStarted=true;compassQuestion=0;compassAnswers=Array(compassQuestions.length).fill(null);compassResult=null;renderCompassTest();return}
 const ans=e.target.closest('[data-compass-answer]');if(ans){compassAnswers[compassQuestion]=Number(ans.dataset.compassAnswer);renderCompassTest();return}
 if(e.target.closest('[data-compass-prev]')&&compassQuestion>0){compassQuestion--;renderCompassTest();return}
 if(e.target.closest('[data-compass-next]')&&compassAnswers[compassQuestion]!==null){if(compassQuestion<compassQuestions.length-1)compassQuestion++;else compassResult=compassScore();renderCompassTest();return}
 if(e.target.closest('[data-compass-reset]')){compassTestStarted=false;compassAnswers=Array(compassQuestions.length).fill(null);compassQuestion=0;compassResult=null;renderCompassTest();return}
});
document.addEventListener('input',e=>{if(e.target.id==='compass-search'){compassSearch=e.target.value;renderCompassMap();const i=$('#compass-search');if(i){i.focus();i.setSelectionRange(i.value.length,i.value.length)}}});
document.addEventListener('change',e=>{if(e.target.id==='compass-a'){compassCompareA=e.target.value;renderCompassCompare()}if(e.target.id==='compass-b'){compassCompareB=e.target.value;renderCompassCompare()}});
translateUI();
